description = "Initialize a project"
prompt = """
Set up the current project.
1. Check if a ./docs folder exists
2. Check if a `./docs/CHECKS.md` exists
3. If `./docs/CHECKS.md` is missing, look through the codebase and determine what automated checks to run after making changes. Consider any linting, type checks, tests, etc.

If either is missing:
1. Inform the user that you will create them.
2. Create `./docs/CHECKS.md` with the appropriate checks as a series of shell commands to run (ex. "npm run lint && npm run check && npm run test").
3. Inform the user that they can edit `./docs/CHECKS.md` to change what checks are run after any changes.

If `./docs/CHECKS.md` exists:
1. Inform the user that the project is already initialized and that they can configure 
"""
